from django.contrib import admin
from .models import *
admin.site.register(UserModel)
admin.site.register(BannerModel)
admin.site.register(CompanyModel)
admin.site.register(OrderModel)
admin.site.register(PaymentModel)
admin.site.register(OutlayModel)
admin.site.register(ActionLogModel)
admin.site.register(ShadowUserModel)
admin.site.register(ShadowBannerModel)
admin.site.register(ShadowOrderModel)
admin.site.register(ShadowPaymentModel)
admin.site.register(BruhModel)
admin.site.register(ShadowBruhModel)
